ALTER TABLE `review_lines` ADD `order_approval_no` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `review_lines` ADD `reading_status` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `review_lines` ADD `delivery_mode` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `review_lines` ADD `order_status` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `review_lines` ADD `delivery_target` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `review_lines` ADD `category` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `review_lines` ADD `order_date` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `review_lines` ADD `deadline_date` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `review_lines` ADD `salesperson` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `review_lines` ADD `maker` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `review_lines` ADD `made_at` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `review_lines` ADD `source_reviewer` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `review_lines` ADD `external_goods_code` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `review_lines` ADD `original_spec` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `review_lines` ADD `transport_spec` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `review_lines` ADD `order_box_qty` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `review_lines` ADD `tax_excluded_unit_price` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `review_lines` ADD `contract_price` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `review_lines` ADD `tax_included_unit_price` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `review_lines` ADD `discount_rate` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `review_lines` ADD `shelf_life_days` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `review_lines` ADD `received_qty` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `review_lines` ADD `gift_rate` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `review_lines` ADD `td` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `review_lines` ADD `da` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `review_lines` ADD `pd` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `review_lines` ADD `spd` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `review_lines` ADD `rebate` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `review_lines` ADD `order_raw_json` text DEFAULT '{}' NOT NULL;